### ISSUE TITLE
Implement shortcodes for public pages

### ISSUE THREAD

**Issue by nielslange** [onionco/wp-seeds#32]
As a user
I want to be able to access a _balance page_
So that I can see how much seeds I have.

As a user
I want to be able to access a _transfer page_
So that I can transfer seeds to another user.

As a user
I want to be able to access a _history page_
So that I can look up all previous transfers.

**Comment by limikael** [comment]
The indivitual shortcodes:

- [] send seeds
- [] show my balance
- [] show my transaction history
