### ISSUE TITLE
Create validation class

### ISSUE THREAD

**Issue by nielslange** [onionco/wp-seeds#63]

**Comment by limikael** [comment]
What is a "validation class"? :) Is it for valitating forms or transactions? in those cases this issue is a duplicate. or is it supposed to validate something else?

**Comment by nielslange** [comment]
> What is a "validation class"? :) Is it for valitating forms or transactions? in those cases this issue is a duplicate. or is it supposed to validate something else?

Due to your form validator, this issue is no longer needed.
