### ISSUE TITLE
Test roles and capabilities

### ISSUE THREAD

**Issue by nielslange** [onionco/wp-seeds#65]
**Subscriber** (default role)

- [ ] Can transfer seeds from their own account to any other account 
- [ ] Can look up their own transactions

**Contributor** (default role)

- [ ] All features that a `Subscriber` has

**Author** (default role)

- [ ] All features that a `Subscriber` has

**Editor** (default role)

- [ ] All features that a `Subscriber` has

**Gardener** (custom role)

- [ ] All features that a `Subscriber` has
- [ ] Can transfer seeds from any account to any other account 
- [ ] Can look up all transactions

**Admin** (default role)

- [ ] All features that a `Gardener` has
- [ ] Can create seeds
- [ ] Can burn seeds

**Comment by limikael** [comment]
As part of solving this issue, please also solve this:

https://github.com/onionco/wp-seeds/issues/55

And close that issue too.
